### ISSUE TITLE
[Reporting Request]: Agency Signed Contracts

### ISSUE THREAD

**Issue by AnthonyRollins** [cal-itp/crm-helpdesk#182]
### What kind of data are you looking for?

We want a way to display the number of `Agency Signed Contracts` (deals custom property) from the payments pipeline. We want to know how many agencies have signed which category contract (A & B).  

### When would you like to receive this report?

Monthly

**Comment by AnthonyRollins** [comment]
The first draft of reports in Hubspot [Dashboard](https://app.hubspot.com/reports-dashboard/5519226/view/10039811).

**Comment by o-ram** [comment]
@AnthonyRollins this looks great! One thing I'm wondering (and if this is not possible, it is so not a big deal), can we also filter the charts to include deals that are only past a certain stage? Since this custom property really only comes into play once an agency has reached Phase 3, it will always look like we don't have this information filled out for most of the deals in the pipeline. And I think that might make this confusing to someone who doesn't have that context, especially the percentage chart. 

If that's an option, I'd love to add that filter in. And if not, then this will work just fine as-is.

**Comment by AnthonyRollins** [comment]
Yeah, I updated the [dashboard](https://app.hubspot.com/reports-dashboard/5519226/view/10039811) to include filters for Phase 2 and on. I included Phase 2 and on because I saw some `agency signed contracts` in Phase 2. I can remove that filter, but I decided to include that.

**Comment by o-ram** [comment]
LGTM! Thanks so much!
