### ISSUE TITLE
[Deals Pipeline Request]: Payments Dashboard

### ISSUE THREAD

**Issue by indiakea** [cal-itp/crm-helpdesk#217]
### Deals Pipeline Request

Payments Dashboard User Research Project 

### Access

india.k@jarv.us, olivia@compiler.la, liz.l@jarv.us, jameelah.y@jarv.us, holly.g@jarv.us, charlie.c@jarv.us

### What problem are you trying to solve for?

In an effort to better support and serve agencies' needs we are conducting user research to assess the efficacy of the Payments Dashboard and to determine potential revisions to its key features, metrics and onboarding process. 

### What is the goal of the pipeline are you trying to solve for?

To track project flow and communication with agencies throughout the research process. 

### Have you used an exisiting pipeline in Hubspot?

None

**Comment by laneymangan** [comment]
Thanks, @indiakea. We're starting to build out this pipeline for you. Do you have an idea of what stages you would like to include? They can be named anything you want and can be changed at any point.

**Comment by indiakea** [comment]
Hey Laney!

I’d like the following stages: (1) Initial contact, (2) Interview
Scheduled, (3) Interview Completed, (4) Insights Indexed. Please let me
know if you have any questions. Thanks!

Best,

India

**Comment by laneymangan** [comment]
[Pipeline ](https://app.hubspot.com/contacts/5519226/objects/0-3/views/all/board)has been built with the above 4 stages.

@indiakea I saw you submitted your user request this morning so that is being processed so you'll have access asap.
Next step will be to build the custom deals (the individual records that will move through the pipeline). Whenever you're ready to do that, we'll just need the name of the deal and the stage you'd like it to start out in (most of the time the name of the deal is a transit agency name but it can be whatever makes sense for your work) Let me know if you have any questions!

**Comment by indiakea** [comment]
Thanks for setting this up! I just saw the link that Anthony sent via
Hubspot. I'll take a look and start acclimating myself to the system. I'll
reach out should I have any questions.

**Comment by laneymangan** [comment]
Pipeline, deals, and custom properties have been created
